// Build pipeline: vite (frontend) → bun --compile (single binary, current platform).
// Cross-targets: pass `--target=linux-x64` or `--target=windows-x64` to override.
//
// Usage:
//   bun scripts/build.ts                 # build for current platform only
//   bun scripts/build.ts --all           # build linux-x64 + windows-x64
//   bun scripts/build.ts --target=linux-x64
//
// Output: build/wb-ai-helper-<target>[.exe]

import { spawn } from 'node:child_process'
import { mkdir, rm, copyFile, writeFile, readdir, stat, rename } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dir, '..')
const BUILD_DIR = path.join(ROOT, 'build')
const WEB_DIST = path.join(ROOT, 'src/web/dist')
const MANIFEST_PATH = path.join(ROOT, 'src/server/embed-manifest.ts')
// Bun's `--compile` rewrites the binary's ELF/PE section in place; FUSE filesystems
// (sshfs, virtiofs in some setups) reject the fd→path lookup and the build aborts.
// We always emit to a tmpfs-backed scratch dir and move the result.
const SCRATCH = path.join(tmpdir(), 'wb-ai-helper-build')

type BunTarget = 'bun-linux-x64' | 'bun-windows-x64' | 'bun-darwin-x64' | 'bun-darwin-arm64'

const argv = Bun.argv.slice(2)
const all = argv.includes('--all')
const explicit = argv
  .find((a) => a.startsWith('--target='))
  ?.slice('--target='.length)

const targets: BunTarget[] = all
  ? ['bun-linux-x64', 'bun-windows-x64']
  : explicit
    ? [normalizeTarget(explicit)]
    : [currentTarget()]

await main()

async function main() {
  console.log('▸ Сборка фронтенда (vite)')
  await sh('bun', ['x', 'vite', 'build'], ROOT)

  console.log('▸ Генерация embed-manifest.ts')
  await writeManifest()

  await mkdir(BUILD_DIR, { recursive: true })
  await mkdir(SCRATCH, { recursive: true })

  for (const target of targets) {
    const outName = nameFor(target)
    const finalPath = path.join(BUILD_DIR, outName)
    const tmpPath = path.join(SCRATCH, outName)
    if (existsSync(finalPath)) await rm(finalPath)
    if (existsSync(tmpPath)) await rm(tmpPath)
    console.log(`▸ Сборка бинарника: ${target} → ${outName}`)
    // Bun 1.3.13 на этом ядре иногда роняет финальную запись ELF/PE-секции
    // ("failed to get path for fd: Unexpected"). Эмпирически:
    //   • с --target=bun-... запись надёжная;
    //   • без --target (host) запись флакает.
    // Поэтому всегда передаём явный таргет и оставляем ретраи на случай редких сбоев.
    const args = [
      'build',
      path.join(ROOT, 'src/server/index.ts'),
      '--compile',
      `--target=${target}`,
      `--outfile=${tmpPath}`,
      '--minify',
      '--sourcemap=none',
    ]
    let lastErr: unknown = null
    for (let attempt = 1; attempt <= 30; attempt++) {
      try {
        await sh('bun', args, ROOT)
        lastErr = null
        break
      } catch (e) {
        lastErr = e
        if (existsSync(tmpPath)) await rm(tmpPath).catch(() => {})
        console.warn(`  попытка ${attempt} не удалась, повтор`)
        await new Promise((r) => setTimeout(r, 500))
      }
    }
    if (lastErr) throw lastErr
    // Cross-device move: rename → copy+unlink fallback.
    try {
      await rename(tmpPath, finalPath)
    } catch {
      await copyFile(tmpPath, finalPath)
      await rm(tmpPath)
    }
    console.log(`✔ ${finalPath}`)
  }

  await writeFile(
    path.join(BUILD_DIR, 'README.txt'),
    [
      'WB Helper — десктопный AI-помощник для Wiren Board.',
      '',
      'Запуск:',
      '   Linux:   ./wb-ai-helper-linux-x64',
      '   Windows: wb-ai-helper-windows-x64.exe',
      '',
      'Браузер откроется автоматически. Если нет — http://127.0.0.1:17321/',
      '',
      'При первом запуске откроется окно "Настройки": вставьте API-ключ',
      'OpenAI-совместимого LLM, нажмите "обновить список", выберите модель',
      'и сохраните. Настройки сохранятся в wb-ai-helper-settings.json рядом с бинарником.',
    ].join('\n'),
  )

  // Восстановим пустой манифест чтобы dev-сборка не тащила хэшированные имена в репо.
  await writeFile(
    MANIFEST_PATH,
    `// Auto-generated; cleared after build. dev-режим отдаст placeholder.\nexport const FILES: Record<string, string> = {}\n`,
  )

  console.log('\nГотово. Файлы в:', BUILD_DIR)
}

async function writeManifest() {
  const files = await walk(WEB_DIST)
  if (!files.length) {
    throw new Error(`пусто в ${WEB_DIST} — сначала vite build`)
  }
  const lines: string[] = []
  const map: string[] = []
  files.forEach((rel, i) => {
    const ident = `f${i}`
    lines.push(`import ${ident} from '../web/dist/${rel}' with { type: 'file' }`)
    map.push(`  ${JSON.stringify(rel)}: ${ident},`)
  })
  const content = `// AUTO-GENERATED by scripts/build.ts. Do not edit.\n${lines.join('\n')}\n\nexport const FILES: Record<string, string> = {\n${map.join('\n')}\n}\n`
  await writeFile(MANIFEST_PATH, content)
}

async function walk(root: string, prefix = ''): Promise<string[]> {
  const out: string[] = []
  for (const entry of await readdir(root)) {
    const abs = path.join(root, entry)
    const rel = prefix ? `${prefix}/${entry}` : entry
    const st = await stat(abs)
    if (st.isDirectory()) out.push(...(await walk(abs, rel)))
    else out.push(rel)
  }
  return out.sort()
}

function nameFor(target: BunTarget): string {
  const flat = target.replace('bun-', '')
  return target === 'bun-windows-x64' ? `wb-ai-helper-${flat}.exe` : `wb-ai-helper-${flat}`
}

function currentTarget(): BunTarget {
  if (process.platform === 'win32') return 'bun-windows-x64'
  if (process.platform === 'darwin') {
    return process.arch === 'arm64' ? 'bun-darwin-arm64' : 'bun-darwin-x64'
  }
  return 'bun-linux-x64'
}

function normalizeTarget(s: string): BunTarget {
  if (s === 'linux-x64' || s === 'bun-linux-x64') return 'bun-linux-x64'
  if (s === 'windows-x64' || s === 'bun-windows-x64') return 'bun-windows-x64'
  if (s === 'darwin-x64' || s === 'bun-darwin-x64') return 'bun-darwin-x64'
  if (s === 'darwin-arm64' || s === 'bun-darwin-arm64') return 'bun-darwin-arm64'
  throw new Error(`Unknown target: ${s}`)
}

function sh(cmd: string, args: string[], cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, { cwd, stdio: 'inherit' })
    p.on('close', (code) =>
      code === 0 ? resolve() : reject(new Error(`${cmd} ${args.join(' ')} exited with ${code}`)),
    )
  })
}
